CREATE SCHEMA IF NOT EXISTS prevoz
    AUTHORIZATION postgres;
CREATE TABLE prevoz.user
(
    user_id  bigint PRIMARY KEY     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    username character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role     character varying(255) NOT NULL
);
CREATE TABLE prevoz.bus
(
    bus_id       bigint PRIMARY KEY     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    number       bigint                 NOT NULL,
    startStation character varying(255) NOT NULL,
    endStation   character varying(255) NOT NULL
);
CREATE TABLE prevoz.minibuss
(
    minibuss_id      bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    number        bigint,
    start_station character varying(255),
    end_station   character varying(255)
);
CREATE TABLE prevoz.ticket
(
    ticket_id   bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id     bigint,
    start_date  character varying(255),
    expiry_date character varying(255),
    FOREIGN KEY (user_id) REFERENCES prevoz.user (user_id)
);
CREATE TABLE prevoz.tram
(
    tram_id      bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    number        bigint,
    start_station character varying(255),
    end_station   character varying(255)
);
CREATE TABLE prevoz.trolley
(
    trolley_id      bigint PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    number        bigint,
    start_station character varying(255),
    end_station   character varying(255)
);
CREATE TABLE prevoz.clock
(
    clock_id    bigint PRIMARY KEY     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tram_id     bigint,
    trolley_id  bigint,
    bus_id      bigint,
    minibuss_id bigint,
    time        character varying(255) NOT NULL,
    FOREIGN KEY (tram_id) REFERENCES prevoz.tram (tram_id),
    FOREIGN KEY (trolley_id) REFERENCES prevoz.trolley (trolley_id),
    FOREIGN KEY (bus_id) REFERENCES prevoz.bus (bus_id),
    FOREIGN KEY (minibuss_id) REFERENCES prevoz.minibuss (minibuss_id)
);


CREATE TABLE prevoz.station
(
    station_id  bigint PRIMARY KEY     NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tram_id     bigint,
    trolley_id  bigint,
    bus_id      bigint,
    minibuss_id bigint,
    name        character varying(255) NOT NULL,
    FOREIGN KEY (tram_id) REFERENCES prevoz.tram (tram_id),
    FOREIGN KEY (trolley_id) REFERENCES prevoz.trolley (trolley_id),
    FOREIGN KEY (bus_id) REFERENCES prevoz.bus (bus_id),
    FOREIGN KEY (minibuss_id) REFERENCES prevoz.minibuss (minibuss_id)
);

